// Rewrites the head of the built index.html so it describes ONE route.
//
// Why this exists: link previews are generated by scrapers that do not run
// JavaScript. WhatsApp, Facebook, Slack, iMessage, LinkedIn and Twitter all read
// the HTML as served. In a client-rendered app that HTML is the same file for
// every route, so every shared link previewed as the Arabic homepage with a
// relative `og:url` of "/" — which is not a URL at all, and the Open Graph spec
// requires an absolute one.
//
// DocumentHead already computes the right tags at runtime from
// window.location.origin. This reuses the same resolver at build time and bakes
// the result into a static file per route, so the scraper and the browser agree.
//
// Arabic on purpose: it is the storefront's default language, and an English
// visitor's browser rewrites the head on load anyway. A scraper has to be given
// one answer, and the default is the honest one.

const ESCAPES = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' };
const attr = (value) => String(value).replace(/[&<>"]/g, (c) => ESCAPES[c]);

// Replace a tag if it is there, otherwise add it. Both matter: the source
// index.html carries most of these already, but a future edit that drops one
// should extend the head rather than silently omit it from every route.
function upsert(html, pattern, tag) {
  if (pattern.test(html)) return html.replace(pattern, tag);
  return html.replace('</head>', `    ${tag}\n  </head>`);
}

function metaProperty(html, property, content) {
  return upsert(
    html,
    new RegExp(`<meta property="${property}" content="[^"]*"\\s*/?>`),
    `<meta property="${property}" content="${attr(content)}" />`
  );
}

function metaName(html, name, content) {
  return upsert(
    html,
    new RegExp(`<meta name="${name}" content="[^"]*"\\s*/?>`),
    `<meta name="${name}" content="${attr(content)}" />`
  );
}

export function renderHead(html, metadata) {
  let out = html;

  out = upsert(out, /<title>[\s\S]*?<\/title>/, `<title>${attr(metadata.title)}</title>`);
  out = metaName(out, 'description', metadata.description);

  out = metaProperty(out, 'og:title', metadata.title);
  out = metaProperty(out, 'og:description', metadata.description);
  out = metaProperty(out, 'og:type', metadata.type);
  out = metaProperty(out, 'og:url', metadata.canonicalUrl);
  out = metaProperty(out, 'og:site_name', metadata.siteName);
  out = metaProperty(out, 'og:locale', metadata.locale);
  out = metaProperty(out, 'og:locale:alternate', metadata.alternateLocale);
  out = metaProperty(out, 'og:image', metadata.imageUrl);
  out = metaProperty(out, 'og:image:alt', metadata.imageAlt);

  out = metaName(out, 'twitter:title', metadata.title);
  out = metaName(out, 'twitter:description', metadata.description);
  out = metaName(out, 'twitter:image', metadata.imageUrl);
  out = metaName(out, 'twitter:image:alt', metadata.imageAlt);

  out = upsert(
    out,
    /<link rel="canonical" href="[^"]*"\s*\/?>/,
    `<link rel="canonical" href="${attr(metadata.canonicalUrl)}" />`
  );

  // Structured data for the crawlers that read it without running scripts.
  // Same id the runtime uses, so DocumentHead replaces this node rather than
  // appending a second copy once React mounts.
  const jsonLd = metadata.structuredData?.length
    ? `<script type="application/ld+json" id="volta-structured-data">${JSON.stringify(
        metadata.structuredData
      ).replace(/</g, '\\u003c')}</script>`
    : '';
  out = out.replace(
    /\s*<script type="application\/ld\+json" id="volta-structured-data">[\s\S]*?<\/script>/,
    ''
  );
  if (jsonLd) out = out.replace('</head>', `    ${jsonLd}\n  </head>`);

  return out;
}

// A build that silently stops substituting is worse than one that fails: the
// deploy looks fine and every link preview is wrong. Checked per file.
export function assertAbsolute(html, route) {
  const relative = [
    ...html.matchAll(/<meta property="og:(?:url|image)" content="([^"]*)"/g),
    ...html.matchAll(/<link rel="canonical" href="([^"]*)"/g),
    ...html.matchAll(/<meta name="twitter:image" content="([^"]*)"/g)
  ]
    .map((m) => m[1])
    .filter((value) => !/^https?:\/\//.test(value));

  if (relative.length) {
    throw new Error(
      `${route}: social tags are still relative (${relative.join(', ')}). ` +
        'A scraper cannot resolve these; check the head rewrite in scripts/socialHead.js.'
    );
  }
}
